apiVersion:   v1
kind:         Service
metadata:
  name:       mysql
  labels:
    run:      mysql
spec:
  type:       ClusterIP
  ports:
  - port:     3306
    protocol: TCP
  selector:
    app:      mysql
