apiVersion:     v1
kind:           Service
metadata:
  name:         petclinic
  labels:
    run:        petclinic
spec:
  ports:
  - port:       80
    targetPort: 8080
    protocol:   TCP
  selector:
    app:        petclinic
  type:         LoadBalancer
