apiVersion:       apps/v1
kind:             Deployment
metadata:
  name:           petclinic
  labels:
    app:          petclinic
    owner:        OleksiiKosyiev
spec:
  replicas:       2
  selector:
    matchLabels:
      app:        petclinic
  template:
    metadata:
      labels:
        app:      petclinic
    spec:
      containers:
      - name:     petclinic
        image:    kosyiev/petclinic:latest
        ports:
        - containerPort: 8080
        env:
          - name: spring.datasource.username
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: username
          - name: spring.datasource.password
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: password
        volumeMounts:
            - mountPath: "/home/ubuntu/config"
              name: pet-data
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 30
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
      volumes:
      - name: pet-data
        configMap:
          name: pet-config
          items:
          - key: application.properties
            path: application.properties
