apiVersion:         v1
kind:               PersistentVolume
metadata:
  name:             pet-data
  labels:
    type:           local
spec:
  storageClassName: manual
  capacity:
    storage:        1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path:           "/root"
